const products=[
{id:'p1',name:'Smart Watch Pro',cat:'Gadget',price:2490,icon:'⌚'},
{id:'p2',name:'Wireless Earbuds',cat:'Gadget',price:1890,icon:'🎧'},
{id:'p3',name:'Premium Backpack',cat:'Fashion',price:1450,icon:'🎒'},
{id:'p4',name:'Luxury Sunglass',cat:'Fashion',price:990,icon:'🕶️'},
{id:'p5',name:'Desk Lamp 3D',cat:'Home',price:1290,icon:'💡'},
{id:'p6',name:'Home Aroma Set',cat:'Home',price:790,icon:'🕯️'}
];
let cart=JSON.parse(localStorage.getItem('cart')||'[]');let cfg={storeWhatsApp:'8801XXXXXXXXX',bkashNumber:'01XXXXXXXXX',nagadNumber:'01XXXXXXXXX'};
const $=s=>document.querySelector(s);const fmt=n=>'৳'+Number(n||0).toLocaleString('en-BD');
fetch('/api/config').then(r=>r.json()).then(j=>{cfg=j;updatePayInfo();}).catch(()=>{});
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('showToast');setTimeout(()=>el.classList.remove('showToast'),2200)}
function renderProducts(){const q=$('#search').value.toLowerCase();const c=$('#category').value;$('#products').innerHTML=products.filter(p=>(c==='all'||p.cat===c)&&p.name.toLowerCase().includes(q)).map(p=>`<article class="card"><div class="productImg">${p.icon}</div><p class="muted">${p.cat}</p><h3>${p.name}</h3><p class="price">${fmt(p.price)}</p><button class="cta" onclick="addCart('${p.id}')">Add to Cart</button></article>`).join('')}
function save(){localStorage.setItem('cart',JSON.stringify(cart));renderCart()}
function addCart(id){const p=products.find(x=>x.id===id);const row=cart.find(x=>x.id===id);if(row)row.qty++;else cart.push({...p,qty:1});save();toast('Added to cart')}
function changeQty(id,d){const r=cart.find(x=>x.id===id);if(!r)return;r.qty+=d;if(r.qty<1)cart=cart.filter(x=>x.id!==id);save()}
function totals(){const subtotal=cart.reduce((s,i)=>s+i.price*i.qty,0);const delivery=subtotal?80:0;return{subtotal,delivery,total:subtotal+delivery}}
function renderCart(){const t=totals();$('#cartCount').textContent=cart.reduce((s,i)=>s+i.qty,0);$('#cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cartRow"><div><b>${i.name}</b><br><small>${fmt(i.price)} × ${i.qty}</small></div><div><button onclick="changeQty('${i.id}',-1)">−</button><button onclick="changeQty('${i.id}',1)">+</button></div></div>`).join(''):'<p class="muted">Your cart is empty.</p>';$('#summaryItems').innerHTML=cart.map(i=>`<div class="summaryRow"><span>${i.name} × ${i.qty}</span><b>${fmt(i.price*i.qty)}</b></div>`).join('')||'<p class="muted">No items selected.</p>';$('#subtotal').textContent=fmt(t.subtotal);$('#delivery').textContent=fmt(t.delivery);$('#total').textContent=fmt(t.total)}
function updatePayInfo(){const m=document.querySelector('input[name="payment"]:checked').value;const trx=$('#trxId');if(m==='bkash'){$('#payNumber').textContent='Send Money to bKash: '+cfg.bkashNumber;trx.style.display='block';trx.required=true}else if(m==='nagad'){$('#payNumber').textContent='Send Money to Nagad: '+cfg.nagadNumber;trx.style.display='block';trx.required=true}else{$('#payNumber').textContent='Cash on Delivery selected.';trx.style.display='none';trx.required=false;trx.value=''}}
async function placeOrder(e){e.preventDefault();if(!cart.length)return toast('Cart is empty');const t=totals();const payment={method:document.querySelector('input[name="payment"]:checked').value,trxId:$('#trxId').value.trim()};const data={customer:{name:$('#name').value,phone:$('#phone').value,email:$('#email').value,address:$('#address').value,note:$('#note').value},payment,items:cart,subtotal:t.subtotal,delivery:t.delivery,total:t.total};try{const res=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await res.json();if(!res.ok)throw new Error(out.message);const msg=encodeURIComponent(`New order from ${data.customer.name}. Total: ${fmt(t.total)}. Payment: ${payment.method}. Order ID: ${out.orderId}`);cart=[];save();toast('Order placed successfully');window.open(`https://wa.me/${cfg.storeWhatsApp}?text=${msg}`,'_blank');e.target.reset();updatePayInfo()}catch(err){toast(err.message||'Order failed')}}
$('#search').addEventListener('input',renderProducts);$('#category').addEventListener('change',renderProducts);document.querySelectorAll('input[name="payment"]').forEach(x=>x.addEventListener('change',updatePayInfo));$('#orderForm').addEventListener('submit',placeOrder);$('#openCart').onclick=()=>$('#cart').classList.add('show');$('#closeCart').onclick=()=>$('#cart').classList.remove('show');renderProducts();renderCart();updatePayInfo();
